### ISSUE TITLE
can not able to get row datas

### ISSUE THREAD

**Issue by arunr307** [bjornharrtell/postgresql-http-server#2]
hai,
when iam try to get row datas it show error message.

http://192.168.1.219:3001/db/test/schemas/public/tables/mytbl/rows/id

{"length":97,"name":"error","severity":"FATAL","code":"28P01","file":"auth.c","line":"302","routine":"auth_failed"}
I use the following command for starting postgresql-http-server.
postgresql-http-server --port 3001 --database test --user postgres --password citrus --raw true  --cors true

When i give a request in 
http://192.168.1.219:3001/db/test/
output as- {"type":"database","children":["schemas"]}.

**Comment by bjornharrtell** [comment]
Sorry it's unlikely that I will put more of my own time into this project, however I've done something very similar for Java which is more complete - https://github.com/bjornharrtell/jdbc-http-server.
