### ISSUE TITLE
Create a join query

### ISSUE THREAD

**Issue by arunr307** [bjornharrtell/postgresql-http-server#4]
Is it possible to create any join query using rest api? if its possible can you give a sample.

**Comment by bjornharrtell** [comment]
Yes using raw SQL.

**Comment by arunr307** [comment]
iam getting an error for join query.
http://localhost:3000/db/test
body:
{
    "sql": "SELECT * FROM party_relation join party_role prol1 ON (1=1)"
}

error:
{"length":83,"name":"error","severity":"ERROR","code":"42601","position":"51","file":"scan.l","line":"1005","routine":"scanner_yyerror"}

can you please help me.
