### ISSUE TITLE
Any issues with the project?

### ISSUE THREAD

**Issue by denismo** [bjornharrtell/postgresql-http-server#7]
Hello,

I tried your project and it looks great for what we need it (expose SQL via HTTP API). However I see that you moved to another project, jdbc based. What are the serious problems (apart from usual time) that made you decide to abandon this project?

Thanks.

Denis

**Comment by bjornharrtell** [comment]
Hi Denis. No technical problems just lost interest and haven't yet found real use cases for it. The JDBC-based project is newer and in some ways more complete but is also more or less abandoned.

**Comment by denismo** [comment]
Cool, good to know. It actually works quite well and fits our use case - we just need a simple way of exposing web analytics data back to client-side Javascript (either raw or after some aggregation/analysis). Don't want to write anything custom as our queries (and data sets) change daily depending on what our analysts produce. And this way, it's all automatic without the need to involve the back-end devs which saves time. So thanks for the project.
